### ISSUE TITLE
where do I edit the snippets?

### ISSUE THREAD

**Issue by mspanish** [yatki/vscode-surround#1]
hi lovely extension! I tried adding js snippets via the snippets manager and they don't show up in your extension - how do I add snippets directly to it?

**Comment by yatki** [comment]
Hey @mspanish, thank you very much for your feedback :))

This extension doesn't use vscode snippet definitions. To Add a new snippet you can go to "Settings" and search for `surround.custom`. And edit it like below:

```
{
  "surround.custom": {
    // identifier must be unique
    "yourCustomIdentifier": { 
      // label must be unique
      "label": "Your custom label",
      "description": "burrito { ... }",
      "snippet": "burrito { $TM_SELECTED_TEXT }$0" // <-- snippet goes here.
    }
  }
}
```

I hope this helps. ✌️
