### ISSUE TITLE
Feature Request - Un-Surround

### ISSUE THREAD

**Issue by atscripter** [yatki/vscode-surround#13]
Un-Surround functionality would simply remove whatever clause surrounding a selected block of code.

[Demo](https://i.imgur.com/i6ktmLp.gif)

**Comment by yatki** [comment]
@atscripter, sorry for late response. I was thinking about this feature request for a while now. 

It really sounds interesting at first glance, but I've asked several developer friends of mine and almost all of them prefers to delete parent closures manually, either with copying the content and pasting over the closure or manually deleting the lines.

So I don't think it is worth the time to develop this feature at the moment. However, feel free to fork this repo and create an "unsurround" extension if you really think it would be useful for the community :)

Thanks for your interest tho 🖖.

**Comment by jwbth** [comment]
> It really sounds interesting at first glance, but I've asked several developer friends of mine and almost all of them prefers to delete parent closures manually, either with copying the content and pasting over the closure or manually deleting the lines.

Yeah, and so much the worse for them. No offense, but that sounds like "Several people say they use horses for transportation – seems that cars will be of no use". I've got to tell you: being able to unwrap code blocks in 1 or 2 clicks/presses is a MASSIVE performance boost.

I haven't done this before; I started doing this now after some 15 years of developer experience. First I wrote my own code snippets using the [native code snippets feature](https://code.visualstudio.com/docs/editing/userdefinedsnippets). But those are substantially limited in functionality, and that wasn't enough. I started using the [Selection Convert](https://github.com/jeff-hykin/selection-convert) extension to write my JavaScript snippets.

Still, having an outside repository of any and all code constructs to unsurround maintained by the community is preferable. Please reopen, and let's see if others have anything to say.

The effects of this are measurable and dramatic, especially in combination with the [shrink/expand selection](https://code.visualstudio.com/docs/editing/codebasics#_shrinkexpand-selection) feature of VS Code. This really saves you from the constant hassle of searching where some block ends (and if it's long, then surprise – after you remove the *starting* bracket, you can't go to the ending bracket by automatic means anymore) and frees up your cognitive resources for meaningful tasks.
