### ISSUE TITLE
Indentation

### ISSUE THREAD

**Issue by johnknoop** [yatki/vscode-surround#2]
Hi. Great extension!

It would be even greater if the inserted code would have the same indentation as the surrounding code.

/john

**Comment by yatki** [comment]
Hey @johnknoop 

Thanks a lot for your feedback :) Nice to hear that you liked it.

Regarding your suggestion, i don't know if I understand your suggestion correctly but I don't think that is the most common use case. The default wrappers that I introduced are mostly reqires indentation for their content. Most style guides or formatters follow that rule at least. So I'd like to stick with that style for the moment :)

But if you like to cancel the indentation for your use case, I'd like to remind that you can modify the surround config and remove the first tab char `\t` from snippet strings.

I hope this helps. Have a great week.

**Comment by yatki** [comment]
The issue is resolved in version 1.2.0. Thanks for reporting the issue.

The release is available on: 
- [VSCode Marketplace](https://marketplace.visualstudio.com/items?itemName=yatki.vscode-surround)
- [GitHub release](https://github.com/yatki/vscode-surround/releases/tag/v1.2.0)

Cheers 🖖,
