### ISSUE TITLE
Custom surround not recognized

### ISSUE THREAD

**Issue by FredyC** [yatki/vscode-surround#5]
I've noticed #3 and I do have 1.0.2 installed. Yet the following is not shown among the _Surround with_ offer.

```json
  "surround.custom": {
    "i18n": {
      "label": "lingui",
      "description": "i18n.t`...`",
      "snippet": "i18n.t`$TM_SELECTED_TEXT`$0",
      "disabled": "false"
    }
  }
```

**Comment by yatki** [comment]
Hey @FredyC, please try to provide disabled: `false` as a **boolean** parameter. You are providing non-empty string which is truthy.
