### ISSUE TITLE
Custom surround not recognized

### ISSUE THREAD

**Issue by gabsinator** [yatki/vscode-surround#51]
Love the extension, just what I was looking for, need some help, not sure what I'm doing wrong, I just can't get it to recognize custom surrounds. 

I have the following in my user settings.json:

I'm on v1.0.2
```
 "surround.custom": {
    "i18n": {
      "label": "i18n",
      "description": "'hello' ==> {t('hello')} ",
      "snippet": "{t($TM_SELECTED_TEXT)}$0",
      "disabled": false
    },
    "yourCommandName": {
      // label must be unique
      "label": "Your Snippet Label",
      "description": "Your Snippet Description",
      "snippet": "burrito { $TM_SELECTED_TEXT }$0", // <-- snippet goes here.
      "disabled": false
    }
  },
```

 - The built in commands work, just not the custom ones.

![image](https://user-images.githubusercontent.com/1658284/65050699-1c87d180-d968-11e9-8b39-d172f878a04e.png)
![image](https://user-images.githubusercontent.com/1658284/65050919-77212d80-d968-11e9-93e9-b360456a3123.png)

**Comment by gabsinator** [comment]
ah! found them under the Quick Pick "surround.with (ctrl+shift+T)" in the command palette.
I was looking under the main list and excpected to find a surround.with.custom / surround.with.mycommand there
![image](https://user-images.githubusercontent.com/1658284/65051192-f878c000-d968-11e9-9d37-df975515920a.png)

sorry, and thanks for this :)

**Comment by yatki** [comment]
@gabsinator hmm, It works perfectly fine with me. Did you try to switch to another tab after applying the settings or restart vscode ? If so which vscode version are you using?

**Comment by yatki** [comment]
Ah ok. Thanks for the feedback. Cheers, 🖖
