### ISSUE TITLE
Can't open settings

### ISSUE THREAD

**Issue by uponatime2019** [yatki/vscode-surround#52]
When I go to settings, search surround with and open a setting it open a settings.json file and not related to surround extension (latest vscode version)

**Comment by yatki** [comment]
Hey @HelloWindowsPhone, sorry I'm not sure if I understood your problem correctly but when you open settings in the JSON view, you can start typing "surround.with." to access settings for existing commands. If you need to add a new command then you have to **copy** and **paste** the code below and **rename** some of the parts as you need.

I hope this helps 🖖 

```
{
  "surround.custom": {
    // command name must be unique
    "yourCommandName": {
      // label must be unique
      "label": "Your Snippet Label",
      "description": "Your Snippet Description",
      "snippet": "burrito { $TM_SELECTED_TEXT }$0" // <-- snippet goes here.
    },
    // You can add more ...
  }
}
```

**Comment by HelloWindowsPhone** [comment]
I make a video to describe issue here. It can't get to the extension settings https://youtu.be/sfyhlDouMpU

**Comment by yatki** [comment]
By the way, if you need to configure a certain command, open the JSON editor. Start typing "surround.with" and press TAB key to auto-complete the setting.

**Comment by HelloWindowsPhone** [comment]
I'm a beginner VSCode user so I always using Settings UI. Thanks I will use JSON editor for configure Surround

**Comment by RogerRU** [comment]
Could you explain (for noobs :-) ) in more detail how to open the JSON editor and edit the settings. Thanks.

**Comment by yatki** [comment]
Hey @RogerRU,

After Opening Settings you can click on the JSON editor icon on the right top of vscode editor.

![image](https://user-images.githubusercontent.com/26697004/70376798-2557c600-190d-11ea-946c-8a1a392d95bc.png)

After than as soon as you start typing surround vscode will guide you to write your configuration.
![image](https://user-images.githubusercontent.com/26697004/70376828-85e70300-190d-11ea-94f1-eb20ce798b86.png)

For custom surround options please see: https://github.com/yatki/vscode-surround#adding-new-custom-wrapper-functions section.

I hope this helps,
Cheers

**Comment by RogerRU** [comment]
Thnx!!!

**Comment by sschnoor** [comment]
Hi @yatki .

I'm hoping to remove all of the shortcuts you placed in there and use my own.  It seems that what you suggested RogerRU do would be the way to do that, however, when I follow those instructions it takes me to the settings.json file, but I don't see any way to delete say the surround.with.if option?  This is what I see, 

![image](https://user-images.githubusercontent.com/12835879/76476818-943b3400-63c0-11ea-9d6d-c5cbc5726408.png)

I am a bit of a noob here, so appreciate any help, I'm sure I missing something obvious!  Thanks!

**Comment by yatki** [comment]
@sschnoor you can use the `disabled: true` to disable the snippets.

**Comment by sschnoor** [comment]
@yatki Thanks.  I realized I misread your instructions to RogerRU.  I see that just typing "surround.with...." in the editor brings up the dialog and the ability to enter disabled: true.  I'm good ! Thanks!
