### ISSUE TITLE
Can't use "$" in custom snippet

### ISSUE THREAD

**Issue by koffielyder** [yatki/vscode-surround#53]
I am trying to create a snippit for time logging of a function

`$start = microtime(true); { $TM_SELECTED_TEXT }$0 $time_elapsed_secs = microtime(true) - $start;`

When i use it it removes the variables (eg $start) i can understand that it works this way but is there any way to show the variable?

**Comment by yatki** [comment]
Hmm could you please try the snippet below:

```
\$start = microtime(true); { $TM_SELECTED_TEXT }$0 \$time_elapsed_secs = microtime(true) - \$start
```
I think you have to escape the dollar signs.

**Comment by koffielyder** [comment]
I already tried that but then it just doesn't write the $

**Comment by yatki** [comment]
Did you try the snippet I just shared? It worked for me... If you still have the problem, could you share your configuration?

**Comment by koffielyder** [comment]
Oh sorry didn't see the double slash I'll try it Thursday when I'm back at the office but I'm sure if it works for you it will work for me, thank you for your help and for the plug-in!

**Comment by koffielyder** [comment]
Yup the double slash did the trick thx for the support!
