### ISSUE TITLE
Python support

### ISSUE THREAD

**Issue by sytelus** [yatki/vscode-surround#55]
It would be great to get python support!

**Comment by yatki** [comment]
Hey @sytelus, thanks for the feedback. 

You are right there are no multiple language support at the moment. https://github.com/yatki/vscode-surround#known-issues 

However, there are a few workarounds to have multiple language support. 

> Hint
> If you want to edit or disable the snippets for only one project and leave them available for others, you can use "Workspace Settings" and disable or add snippets for only one project.

I'm already considering to add language support for the snippets in the new version, until then I hope this helps.

**Comment by yatki** [comment]
duplicate #6

**Comment by yatki** [comment]
@sytelus just FYI, I've resolved this issue in version 1.1.1 while adding some new features. Thanks for reporting the issue.

The release is available on: 
- [VSCode Marketplace](https://marketplace.visualstudio.com/items?itemName=yatki.vscode-surround)
- [GitHub release](https://github.com/yatki/vscode-surround/releases/tag/v1.1.1)

Cheers 🖖,
