### ISSUE TITLE
Automatically surround selected text

### ISSUE THREAD

**Issue by bmix** [yatki/vscode-surround#56]
Is it possible to have selected text surrounded automatically from a limited set of characters?

Let's assume I have the symbol `foobar` and want it to become `"foobar"`. So I would select it and just type (without opening up the "surround with" menu) `"` and the result would be an automatic surrounding with a starting and an ending `"`.

It would make sense (configurable) for:

- `"` -> `"`
- `'` -> `'`
- `{` -> `}`
- `(` -> `)`
- `[` -> `]`
- `<` -> `>`  (if you add a callback option here, where the user writes the callback, it could even add the closing element tag or differentiate between empty and non empty tags)
- `/` -> `/`
- `@` -> `@` (in this case, maybe a repeated use of `@` would need to be recognized. So `@@` -> `@@`)
- any comment delimiters, that have an opening and a closing symbol. XQuery example: `(:` -> `:)`

I did not install the extension, since such feature is not mentioned in the documentation. Should this feature be missing, could you please think about it? Thank you! :-)

**Comment by yatki** [comment]
Hey @bmix,

All the surround options except the last 3 are already supported by vscode (at least for js). So, you don't need an extension for them. However, for the last 3, you can use this extension. So the answer is YES. 

Please check https://github.com/yatki/vscode-surround#adding-new-custom-wrapper-functions to add your custom functions.

As an example:
```
{
  "surround.custom": {
    // command name must be unique
    "yourCommandName": {
      // label must be unique
      "label": "Your Snippet Label",
      "description": "Your Snippet Description",
      "snippet": "(: $TM_SELECTED_TEXT :)$0" // <-- snippet goes here.
    },
    // You can add more ...
  }
}
```

Cheers,

**Comment by bmix** [comment]
Great! Thanks for pointing out.

But can I use your proposed solution (using 'yatki/vscode-surround#adding-new-custom-wrapper-functions') without bringing up the menu? By just typing the configured starting character? That would be really great!
