### ISSUE TITLE
If no results found, take search input as default

### ISSUE THREAD

**Issue by mschmidtkorth** [yatki/vscode-surround#57]
**Problem:** Typically you have snippets for your most used functions. However, sometimes you might want to surround something with a function you rarely use, that is new etc.

**Idea:** If the search returns no results, offer the user to use the search term literally and wrap the selected text in (selection)
- `$SEARCH_TERM($TM_SELECTED_TEXT)$0`
- `$SEARCH_TERM[$TM_SELECTED_TEXT]$0`
- `$SEARCH_TERM{$TM_SELECTED_TEXT}$0`
These are just examples.

This would add another layer of flexibility.

**Comment by yatki** [comment]
Hmm. @mschmidtkorth thank you very much for the idea. It sounds interesting for sure. I'll check if there is an existing solution for this in vscode and if not, see what I can do about this.

Cheers,

**Comment by yatki** [comment]
Hey @mschmidtkorth, again thank you very much for the idea. I started to work on this issue and it's not hard to add this feature. However, after giving it a thought, I couldn't come up with a really useful case for this feature. If someone needs to type the same thing over a selection they can use the multiple cursor feature of vscode or create a snippet.

I think the best feature is no feature and I don't want to add more complexity to the extension :) So, for the moment I won't be implementing this feature. 

Have a great week.
