### ISSUE TITLE
Place cursor in snippet

### ISSUE THREAD

**Issue by erralb** [yatki/vscode-surround#58]
Hi, and thanks for this really useful extension.

Is it possible to place the cursor in the snippet, something like $TM_SELECTED_TEXT, but instead (or both) having the cursor placed somewhere instead of at the end of the inserted snippet ?

(Basically, I would like to add the snippet then hit paste to copy something inside)

Cheers

**Comment by yatki** [comment]
Hey @erralb, sure it's possible. You can edit the snippets config and put `$0` as your tabstop anywhere in the snippet. You can also add `$1`, `$2`,.. etc to add as many stop points as you like.

You can find more info here: https://code.visualstudio.com/docs/editor/userdefinedsnippets#_tabstops

I hope this helps.
Cheers🖖🏻,
