### ISSUE TITLE
Surround With <element>replacement state

### ISSUE THREAD

**Issue by sdunnin** [yatki/vscode-surround#62]
When performing a Surround With: <element></element> and after the insertion is completed the editor is left in Column Select Mode with a cursor at both the opening and closing inserted elements

**Comment by sdunnin** [comment]
To expand on my first comment a bit. When finished entering the tag or element name it would be nice if you could finish the operation with a enter or tab versus having to press esc twice to exit column select mode. Additionally, it would be nice if upon completion it was able to format the selection or at least the document.

**Comment by yatki** [comment]
Hey @sdunnin, Thank you very much for the issue. The issue you are describing is actually what I intended to achieve. So we are facing a "It's not a bug, it's a feature" situation 😅 

So the idea is: 
1. You wrap your text with an element. 
2. You type your element's name (so the close tag is also written).
3. You hit the tab key and start writing attributes. If you don't need to write attributes hit the tab again and quit the snippet.

If this is not the behavior what you can edit "surround.with.element" config and replace the snippet with something like:

```jsonc
{
    "snippet": "<${1}>$TM_SELECTED_TEXT</$1>$0",
}

I hope this helps. Cheers,

```
