### ISSUE TITLE
surround with element not showing in jsx (.js) files...

### ISSUE THREAD

**Issue by alexgv99** [yatki/vscode-surround#69]
It used to work, but, today, I'm trying encapsulate some text into an element and the element didn't show in popup among other options. However, It work just fine if I run the surround.with.element command.

![image](https://user-images.githubusercontent.com/6002790/125857763-ace2c857-532c-4b8e-9d64-5153e92d7bad.png)

![image](https://user-images.githubusercontent.com/6002790/125857835-95cda800-028a-4a01-a893-3a7ffc233a67.png)

![image](https://user-images.githubusercontent.com/6002790/125857880-d3f838b2-adef-4689-bf0a-a255a44d5ac2.png)

**Comment by yatki** [comment]
Hey @alexgv99, Thanks for reporting the issue. With the new version, I added language support to the extension.

So By default element wrapper only works with  "html", "typescriptreact", "javascriptreact", "jsx", "markdown".

Most people are using .jsx as a file extension in their react components. Maybe you can also rename your files to have `.jsx` extension.

If you want to continue working in js file however you can add javascript to existing `languageIds` as below:

```
 "surround.with.element": {
          "type": "object",
          "default": {
            "label": "<element></element>",
            "description": "<element>...</element>",
            "disabled": false,
            "snippet": "<${1}$2>$TM_SELECTED_TEXT</$1>$0",
            "languageIds": [
              "html",
              "typescriptreact",
              "javascriptreact",
              "jsx",
              "markdown",
              "javascript"
            ]
          }
        },
```

Or you can use 
```
"files.associations": {
    "*.js": "javascriptreact"
}
```
See: https://stackoverflow.com/questions/45558193/how-to-make-vs-code-change-language-to-javascript-react-when-open-a-jsx-file/51640555

I prefer just to use `jsx` extensions but you can choose how you want to proceed.

I hope this helps.

Cheers,
