### ISSUE TITLE
Remove `multi selection` reference from readme

### ISSUE THREAD

**Issue by mikeerickson** [yatki/vscode-surround#75]
As per your latest note

> Fixes #74 - Multi selection is no longer supported starting from version 1.2.0

Might want to remove this "feature" listed in README

**Comment by yatki** [comment]
Hey @mikeerickson thanks for message. I think there was a misunderstanding there.. There was a problem with multi selection and i actually fixed that bug :)

So multi selection is still supported :)🖖🏻😁
