### ISSUE TITLE
[Feature Request] Add a way to customize placeholder variables

### ISSUE THREAD

**Issue by ffxsam** [yatki/vscode-surround#77]
When I surround this with try/catch:

```ts
test();
```

I get this:
```ts
try {
  test();
} catch (err) {
  
}
```

I always write `catch (e)` in my code, so it would be handy if we could somehow customize these code snippets. But obviously not the end of the world if it doesn't happen. 😉

**Comment by yatki** [comment]
@ffxsam it is actually possible,

```json5
 {
  // ...
  // at the end of your vscode settings JSON,
  "surround.with.tryCatch": {
    "type": "object",
    "default": {
      "label": "try/catch",
      "description": "try { ... } catch (e) { $catchBlock }",
      "disabled": false,
      "snippet": "try {\n\t$TM_SELECTED_TEXT\n} catch (e) {\n\t$1\n}$0"
    }
  },
}
```

Just paste this in your settings, in order to override your existing setting. You can do this for any snippet or add your own snippets using `surround.custom` settings key. See the readme file for details.

Cheers,
Mehmet

**Comment by yatki** [comment]
Sorry I copied the wrong setting at first, the updated one should work fine..

**Comment by ffxsam** [comment]
@yatki Thanks! My mistake, I completely missed this.
