### ISSUE TITLE
Snippets not inserted when nothing is selected

### ISSUE THREAD

**Issue by JordanMandel** [yatki/vscode-surround#80]
I know the extension is called "Surround", implying you need to surround _something_ :) However this actually used to work with the extension: you used to be able to insert a snippet with nothing selected. But in some recent update (last couple of months?) you have to have something selected for a snippet to be inserted.  Would it be possible to make this work again without a selection? Thanks!

**Comment by yatki** [comment]
Hey @JordanMandel,

You can go to Keyboard Shorcuts, search for **surround** basically remove the `editorHasSelection` condition from the **When** Expression. 

That should help. 🖖🏻 

![image](https://user-images.githubusercontent.com/26697004/166241068-a5d5c04e-0869-49b7-8d8e-6324fe69726c.png)

**Comment by JordanMandel** [comment]
Hi, thanks for the response. Unfortunately, that's not quite the issue. I already have the shortcut bound without any conditions
![image](https://user-images.githubusercontent.com/2067843/166297198-7f1c7909-69b5-4ab3-b28f-4ff05ed756ac.png)

So, the menu of surround snippets appear just fine, but if there is no selection, then no snippet gets inserted into the editor.

**Comment by JordanMandel** [comment]
Snippets are another option, but I prefer your extension :) I'll give you an example of a use case where this change gets in my way. 

I have a surround-with template for inserting PowerShell functions. Sometimes I have a piece of code at the global level that I want to wrap into a function and then surround-with works fine for this.  But often I just want to create a blank function. To do that right now I have to type a dummy piece of text, surround it, and then delete the dummy text. 

I'd rather not create a snippet for this because then if I want to make changes to my template, I'd need to change it two places: once for the surround-with and once for the snippet.  I want only one definition of a snippet/surround-with block.

**Comment by carllerche** [comment]
I found this issue when I hit the same case.

Personally, my expectation for running "surround" with no selection is it would default to the current line.

**Comment by yatki** [comment]
Hmm. Ok, I'll add it back :D

**Comment by yatki** [comment]
🎉 This issue was resolved in version 1.4.0 🎉

The release is available on: 
- [VSCode Marketplace](https://marketplace.visualstudio.com/items?itemName=yatki.vscode-surround)
- [GitHub release](https://github.com/yatki/vscode-surround/releases/tag/v1.4.0)

Don't forget to update your extension and leave a star :)
Cheers🖖🏻,
