### ISSUE TITLE
need some help

### ISSUE THREAD

**Issue by msalgado618** [yatki/vscode-surround#94]
ADD ISSUE DESCRIPTION HERE

Version: 1.77.3
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Embedder: vscode.dev

Extension version: 1.5.0

**Comment by yatki** [comment]
sorry @msalgado618, did you forget to explain the issue? It's not clear how I can help at the moment.
