### ISSUE TITLE
surround w template literal variable working as intended?

### ISSUE THREAD

**Issue by Hifilo** [yatki/vscode-surround#95]
The template literal variable command doesn't seem to consider if the selected word is currently in a quoted sentence

![Code_6RvlW85TM8](https://user-images.githubusercontent.com/92943726/235351777-a7c7b046-6b61-445a-8cc6-3d365adcb83e.gif)

I made a custom one for my use case, but thought I'd pass along the bug.

Cheers

**Comment by yatki** [comment]
Hmm. That's not an easy fix. Surround only knows the selected text. I think there is no solution for this other than having a custom snippet for just adding `${ ... }` without backticks. Thank you very much for reporting this tho 🖖🏻
